name: Generate PMTiles

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 1 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-tiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tippecanoe
        run: |
          sudo apt-get update
          sudo apt-get install -y tippecanoe

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests shapely pyproj huggingface_hub

      - name: Generate PMTiles
        env:
          PYTHONUNBUFFERED: "1"
        run: python main.py

      - name: Upload to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        if: hashFiles('openaip.pmtiles') != ''
        run: python upload_to_hugging_face.py

      - name: Upload PMTiles artifact
        if: hashFiles('openaip.pmtiles') != ''
        uses: actions/upload-artifact@v4
        with:
          name: pmtiles-outputs
          path: openaip.pmtiles

      - name: Update Generated Date in Webpage
        run: python update_web.py

  deploy-pages:
    needs: build-tiles
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload index.html artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
